stages:
  - test
  - release

services: []

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.3.1
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-gitlab-release@0.3.1
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-to-pypi@0.3.1

test:
  stage: test
  image: "registry.gitlab.com/thelabnyc/python:${IMAGE}"
  script:
    - pip install tox
    - tox
  coverage: '/^TOTAL.+?(\d+\%)$/'
  parallel:
    matrix:
      - IMAGE: py312
        TOX_SKIP_ENV: "^(?!py312-)"
      - IMAGE: py313
        TOX_SKIP_ENV: "^(?!py313-)"
