stages:
  - test

services: []

before_script:
  - pip install tox

test_python:3.4:
  stage: test
  image: python:3.4
  script: tox --skip-missing-interpreters

test_python:3.5:
  stage: test
  image: python:3.5
  script: tox --skip-missing-interpreters

test_python:3.6:
  stage: test
  image: python:3.6
  script: tox --skip-missing-interpreters
