stages:
  - test

services: []

include:
  - project: thelabnyc/gitlab-ci-templates
    file: /ci/sast.gitlab-ci.yml

test_python:3.5:
  stage: test
  image: python:3.5
  script:
    - pip install tox
    - tox -e 'py35-django{111,220}'

test_python:3.6:
  stage: test
  image: python:3.6
  script:
    - pip install tox
    - tox -e 'py36-django{111,220}'

test_python:3.7:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e 'py37-django{220}'

test_python:3.8:
  stage: test
  image: python:3.8
  script:
    - pip install tox
    - tox -e 'py38-django{220}'
