stages:
  - test

services: []

test:
  stage: test
  image: $IMAGE
  script:
    - pip install tox
    - tox -e $TOX_ENVS
  parallel:
    matrix:
      - IMAGE: python:3.7
        TOX_ENVS: py37-django{220,300,310}

      - IMAGE: python:3.8
        TOX_ENVS: py38-django{220,300,310}

      - IMAGE: python:3.9
        TOX_ENVS: py39-django{220,300,310}
